version: '3.6'

services:
  mongodb:
    image: mongo:4.0-xenial
    hostname: mongo
    ports:
      - "27017:27017"
    networks:
      - resto-commande

 # api_back:
 #   build:
 #       context: .
 #       dockerfile: ./Dockerfile
 #   ports:
 #     - "9000:9000"
 #   depends_on:
 #     - mongodb
 #   networks:
 #     - resto-commande
 #   environment:
 #     - WAIT_HOSTS=mongodb:27017
 #     - WAIT_HOSTS_TIMEOUT=300
 #     - WAIT_SLEEP_INTERVAL=30
 #     - WAIT_HOST_CONNECT_TIMEOUT=30

networks:
  resto-commande : {}
volumes:
  data: