version: '3'
 
services:
  mongo_db:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: DBapiBack
    networks:
      - resto-commande

  api-rest-back:
    build:
        dockerfile: ./api-rest-back/Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mongo_db
    environment: 
      - MONGO_URL=mongodb://mongo_db:27017/DBapiBack
    networks:
      - resto-commande
  
  backoffice:
    build:
      dockerfile: ./cours-api-rest-backoffice/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - mongo_db
      - api-rest-back
    environment:
      VITE_API_URL: http://api-rest-back:9000/api
    networks:
      - resto-commande

networks:
  resto-commande:
    driver: bridge